[package]
name = "t"
version = "0.1.0"
authors = ["nextzhou <nextzhou@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
itertools = "0.7.3"
time = "0.1.40"
lazy_static = "1.2.0"
regex = "1.0.6"